
name: CI and Deploy to GitHub Pages  
 
on:   
  push:
    branches: [main]
  pull_request:
    branches: [main] 
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Install Allure Command Line
        run: npm install -g allure-commandline  

      - name: Run Playwright tests with configured reporters
        run: npx playwright test
        continue-on-error: true

      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y-%m-%d__%H%M%S)"

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report/${{ steps.timestamp.outputs.timestamp }}/

      - name: Zip Allure report
        run: zip -r ${{ steps.timestamp.outputs.timestamp }}/allure-report.zip allure-report/${{ steps.timestamp.outputs.timestamp }}

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{ steps.timestamp.outputs.timestamp }}
          path: ${{ steps.timestamp.outputs.timestamp }}/allure-report.zip


  
