name: CI and Deploy Allure Report to GitHub Pages

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main] 

jobs: 
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright@1.43.1

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=allure
        continue-on-error: true

      - name: Setup Allure Commandline
        run: sudo npm install -g allure-commandline

      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d__%H%M%S')" >> $GITHUB_ENV

      - name: Create timestamped directory for reports
        run: mkdir -p allure-history/${{ env.TIMESTAMP }}

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-history/${{ env.TIMESTAMP }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "gh-pages" ]; then
            git reset --soft origin/gh-pages || true
          fi

      - name: Copy latest Allure report to its timestamp directory
        run: cp -r allure-history/${{ env.TIMESTAMP }}/* allure-history/${{ env.TIMESTAMP }}

      - name: Copy index.html to root
        run: cp allure-history/${{ env.TIMESTAMP }}/index.html .

      - name: Commit Allure report and index.html to gh-pages
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Deploy Allure report ${{ env.TIMESTAMP }}"
          else
            echo "No changes to commit to gh-pages."
          fi

      - name: Push changes using PAT
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN2 }}
        run: git push -fu https://${ACCESS_TOKEN}@github.com/${{ github.repository }} gh-pages

      - name: Output Allure report URL
        run: |
         echo "Allure report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allure-history/${{ env.TIMESTAMP }}"
         echo "Access the latest report at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
