name: CI and Deploy Allure Report to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright@1.43.1

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d__%H%M%S')" >> $GITHUB_ENV

      - name: Create timestamped directory for reports
        run: mkdir -p allure-history/${{ env.TIMESTAMP }}

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: "allure-history/${{ env.TIMESTAMP }}"
          allure_results: allure-results

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "gh-pages" ]; then
            git reset --soft origin/gh-pages || true
          fi

      - name: Stash existing changes
        run: git stash

      - name: Set permissions for allure-report directory
        run: |
          mkdir -p allure-report
          sudo chmod -R 777 allure-report

      - name: Apply stash
        run: git stash pop

      - name: Copy latest Allure report to gh-pages
        run: |
          cp -r allure-history/${{ env.TIMESTAMP }} allure-report
          cp -r allure-history/${{ env.TIMESTAMP }}/* .

      - name: Commit Allure report to gh-pages
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Deploy Allure report ${{ env.TIMESTAMP }}"
          else
            echo "No changes to commit to gh-pages."
          fi

      - name: Push changes using PAT
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN2 }}
        run: |
         git push -fu https://${ACCESS_TOKEN}@github.com/${{ github.repository }} gh-pages

      - name: Output Allure report URL
        run: |
         echo "Allure report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allure-history/${{ env.TIMESTAMP }}"
