name: CI and Deploy Allure and Playwright Reports to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright@1.43.1

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      - name: Change permissions for files
        run: sudo chmod -R u+w .

      - name: Generate Allure results
        run: npx allure generate allure-results --clean -o allure-report

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y-%m-%d__%H%M%S)" >> $GITHUB_ENV

      - name: Create timestamped directory for reports
        run: mkdir -p reports/playwright/${{ env.timestamp }} reports/allure/${{ env.timestamp }}

      - name: Copy Playwright report to timestamped directory
        run: cp -r playwright-report/* reports/playwright/${{ env.timestamp }}

      - name: Copy Allure report to timestamped directory
        run: cp -r allure-report/* reports/allure/${{ env.timestamp }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Stash package files to prevent checkout issues
        run: git stash push -- package-lock.json package.json

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "gh-pages" ]; then
            git reset --soft origin/gh-pages || true
          fi

      - name: Remove all except index.html and timestamped directories
        run: |
          sudo chmod -R u+w . 
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name 'reports' ! -name 'index.html' -exec rm -rf {} + || true

      - name: Copy reports to root
        run: cp -r reports/* .

      - name: Create or Update Root index.html
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Reports</title>
          </head>
          <body>
            <h1>Reports</h1>
            <ul>
              <li><a href="reports/allure/latest">Latest Allure Report</a></li>
              <li><a href="reports/playwright/latest">Latest Playwright Report</a></li>
            </ul>
          </body>
          </html>' > index.html

      - name: Update Latest Allure Report
        run: |
          rm -f reports/allure/latest
          ln -s ${{ env.timestamp }} reports/allure/latest

      - name: Update Latest Playwright Report
        run: |
          rm -f reports/playwright/latest
          ln -s ${{ env.timestamp }} reports/playwright/latest

      - name: Commit Allure and Playwright reports to gh-pages
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Deploy reports"
          else
            echo "No changes to commit to gh-pages."
          fi

      - name: Push changes using PAT
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN2 }}
        run: git push -fu https://${ACCESS_TOKEN}@github.com/guneyekiz/playwright gh-pages

      - name: Output Allure report URL
        run: |
         echo "Allure report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/reports/allure/${{ env.timestamp }}"

      - name: Output Playwright report URL
        run: |
         echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/reports/playwright/${{ env.timestamp }}"
