name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [ main, maidn ]
  pull_request:
    branches: [ main2, maine ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm install playwright@1.43.1

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y-%m-%d__%H%M%S)" >> $GITHUB_ENV

      - name: Create timestamped directory for Playwright reports
        run: mkdir -p ${{ env.timestamp }}

      - name: Zip Playwright report
        run: zip -r ${{ env.timestamp }}/playwright-report.zip playwright-report/

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ env.timestamp }}
          path: ${{ env.timestamp }}/playwright-report.zip

      - name: Copy Playwright report to timestamped directory
        run: cp -r playwright-report/* ${{ env.timestamp }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages:gh-pages || true

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "gh-pages" ]; then
            git reset --soft origin/gh-pages || true
          fi

      - name: Remove all except index.html and timestamped directories
        run: |
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name '202*' ! -name 'index.html' -exec rm -rf {} + || true

      - name: Commit Playwright report to gh-pages
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Deploy Playwright report ${GITHUB_SHA}"
          else
            echo "No changes to commit to gh-pages."
          fi

      - name: Push changes using PAT
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN2 }}
        run: |
          git push -fu https://${ACCESS_TOKEN}@github.com/guneyekiz/playwright gh-pages
