name: CI and Deploy Allure Report to GitHub Pages

on:
  push: 
    branches: [mainds]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright@1.43.1

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests and generate Allure results
        run: npx playwright test --reporter=allure
      
      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Install HTTP Server for testing
        run: npm install http-server

      - name: Test Allure Report Locally
        run: |
          npx http-server allure-report &
          sleep 10
          curl http://localhost:8080/index.html

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages --depth=1

      - name: Checkout gh-pages branch
        run: git checkout gh-pages || git checkout --orphan gh-pages

      - name: Remove old files
        run: git rm -rf . && mkdir allure-history

      - name: Copy new Allure report files to gh-pages
        run: cp -r ../allure-report/* allure-history/

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy updated Allure report to GitHub Pages"

      - name: Push changes to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

      - name: Output Allure report URL
        run:  |
         echo "Allure report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allure-history/current"
