name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright@1.43.1

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests with configured reporters
        run: npx playwright test
        continue-on-error: true

      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d__%H%M%S')" >> $GITHUB_ENV

      - name: Print timestamp
        run: |
          echo "Timestamp: $TIMESTAMP"
          echo "GITHUB_ENV content:"
          cat $GITHUB_ENV

      - name: Create timestamped directory for reports
        run: |
          mkdir -p allure-history/$TIMESTAMP
          echo "Created directory: allure-history/$TIMESTAMP"

      - name: Print directory structure before report generation
        run: ls -R

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: "allure-history/$TIMESTAMP"
          allure_results: allure-results

      - name: Copy allure-results to timestamped directory
        run: cp -r allure-results/* allure-history/$TIMESTAMP/

      - name: Print directory structure after report generation
        run: ls -R allure-history/$TIMESTAMP

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages

      - name: Checkout gh-pages branch
        run: git checkout gh-pages

      - name: Merge changes
        run: git merge origin/gh-pages --allow-unrelated-histories

      - name: Commit and Push
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add allure-history/$TIMESTAMP
          git commit -m "Add report for $TIMESTAMP"
          git push origin gh-pages
