name: Continuous Integration and Deployment

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies and Playwright
        run: npm ci && npm install playwright
      
      - name: Install Playwright browsers
        run: npx playwright install
      
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
      
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Stash changes including untracked files
        run: git stash push --include-untracked
      
      - name: Checkout gh-pages branch or create it if doesn't exist
        run: |
          if git branch -r | grep gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial commit for gh-pages"
            git push origin gh-pages
          fi
      
      - name: Clear current gh-pages content
        run: git rm -rf . || echo "No files to remove."
      
      - name: Restore the content from stash or commit
        run: |
          git stash apply || echo "No stash to apply."
          git add -f playwright-report || echo "No playwright-report to add."
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
          else
            git commit -m "Deploy updated Playwright report [skip ci]"
            git push origin gh-pages
          fi
      
      - name: Output Playwright report URL
        run: |
         echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/index.html"
