name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload HTML report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/

  publish_report:
    needs: test
    if: "success() || needs.test.result == 'failure'"
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if gh-pages branch exists
        id: check_branch
        run: |
          if git branch -r | grep "origin/gh-pages"; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create gh-pages branch if not exists
        if: steps.check_branch.outputs.exists == 'false'
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"
          git push origin gh-pages

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Clear existing files
        run: git rm -rf . && mkdir reports && touch .gitkeep

      - name: Commit cleared state
        run: |
          git add . && git commit -m "Clear gh-pages branch" || echo "No changes to commit"

      - name: Push cleared state
        run: git push origin gh-pages

      - name: Download zipped HTML report
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: .

      - name: Get the current date and time
        id: date
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Move reports to gh-pages branch
        run: |
          mkdir -p reports/${{ steps.date.outputs.NOW }}
          mv playwright-report/* reports/${{ steps.date.outputs.NOW }}/
          git add reports/${{ steps.date.outputs.NOW }}

      - name: Update index.html to redirect to the latest report
        run: |
          echo '<meta http-equiv="refresh" content="0; URL=reports/${{ steps.date.outputs.NOW }}/index.html" />' > index.html
          git add index.html

      - name: Commit and push reports
        run: |
          git commit -m "Update reports"
          git push origin gh-pages
