name: Continuous Integration and Deployment

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies and Playwright
        run: |
          npm ci
          npm install playwright
      
      - name: Install Playwright browsers
        run: npx playwright install
      
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
      
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      
      - name: Prepare for Deployment
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git stash --include-untracked
      
      - name: Deploy to gh-pages
        if: success()
        run: |
          git fetch --depth=1 origin gh-pages || true
          if ! git branch -r | grep -q 'origin/gh-pages'; then
            git checkout --orphan gh-pages
            git rm -rf .
            git clean -fdx
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
          fi
          git checkout -f gh-pages
          git rm -rf .
          git checkout stash -- .
          git add -f playwright-report
          git commit -m "Update Playwright Report"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Output Report URL
        run: |
          echo "Playwright report URL: https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)/playwright-report/index.html"
