name: CI and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright and browsers
        run: |
          npm install playwright
          npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages || true  # Fetch gh-pages branch, don't fail if it doesn't exist

      - name: Switch to gh-pages branch or create it
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            # If gh-pages branch exists, switch to it
            git checkout gh-pages
            git reset --hard origin/gh-pages
          else
            # If gh-pages branch does not exist, create it
            git checkout --orphan gh-pages
            git rm -rf .
            git clean -fdx
            git commit --allow-empty -m "Initial commit on gh-pages"
            git push origin gh-pages
          fi

      - name: Deploy Playwright Report to gh-pages
        run: |
          git rm -rf . || true  # Remove all files from the working tree
          git clean -fdx  # Remove all untracked files and directories
          # Copy the new report
          cp -R ../playwright-report/ . || echo "Copy failed: Playwright report not found."
          # Add all changes to git
          git add .
          # Commit and push if there are new changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Deploy Playwright report"
            git push -f origin gh-pages
          else
            echo "No changes to deploy."
          fi

      - name: Output Playwright report URL
        run: | 
          echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/"
