name: CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright and browsers
        run: |
          npm install playwright
          npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html --output=playwright-report

      - name: Upload Playwright report as an artifact (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      
      - name: Deploy to GitHub Pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # Setup git with GitHub Actions bot
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Check if gh-pages branch exists
          if git ls-remote --exit-code origin gh-pages; then
            git fetch origin gh-pages:gh-pages
            git worktree add gh-pages gh-pages
          else
            git worktree add gh-pages HEAD
            git -C gh-pages checkout --orphan gh-pages
          fi
          
          # Clean gh-pages branch content and copy new report
          rm -rf gh-pages/*
          cp -R playwright-report/* gh-pages/
          
          # Commit and push changes
          git -C gh-pages add --all
          git -C gh-pages commit -m "Deploy Playwright report to GitHub Pages" || echo "No changes to commit"
          git -C gh-pages push --force "https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}" gh-pages

