name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Updated to v3
    - name: Use Node.js
      uses: actions/setup-node@v3 # Updated to v3
      with:
        node-version: '14' # You can specify a newer version of Node.js if your project allows
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npm test
  
    - uses: actions/upload-artifact@v3 # Updated to v3
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
        
    - name: Get Allure history
      uses: actions/checkout@v3 # Updated to v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    # This action might not have a newer version, please verify if there's an update available
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3 # Updated to v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages # Changed to `publish_branch`, as `PUBLISH_BRANCH` is for environment variables
        publish_dir: ./allure-report # Updated to reflect the directory that contains your index.html
