name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload HTML report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }} # Use a PAT with repo scope

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download zipped HTML report
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: temp

      - name: Prepare directories and move reports
        run: |
          NOW=$(date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p reports/$NOW
          mv temp/playwright-report/* reports/$NOW/
          # Ensure the directory for this report has its own index.html for archival
          echo "<meta http-equiv='refresh' content='0; URL=./index.html' />" > reports/$NOW/index.html
          # Update the root index.html to redirect to the latest report
          echo "<meta http-equiv='refresh' content='0; URL=reports/$NOW/index.html' />" > index.html
          git add reports/$NOW/ index.html

      - name: Commit and push changes
        run: |
          if git commit -m "Deploy updated reports for $NOW"; then
            git push origin gh-pages
          else
            echo "No changes to commit."
          fi
