name: CI and Deploy to GitHub Pages  

on:   
  push:
    branches: [main]
  pull_request:
    branches: [main] 
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Run Playwright tests
        run: npx playwright test --reporter=html,allure-playwright
        continue-on-error: true

      - name: Generate Allure report
        run: npx allure generate --clean --output allure-report

      - name: Add and commit reports
        run: |
          git add allure-report/* playwright-report/*
          git commit -m "Update reports ${GITHUB_SHA}" || echo "No changes to commit."

      - name: Push changes to gh-pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN2 }}
        run: |
          git push -fu https://${ACCESS_TOKEN}@github.com/guneyekiz/playwright gh-pages

      - name: Output report URLs
        run: | 
          echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/"
          echo "Allure report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allure-report/"
