name: Playwright Tests on Guney Branch
on:
  push:
    branches: [guney] # Run actions on pushes to the guney branch
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  publish_report:
    name: Publish HTML Report to gh-pages
    if: "success() || needs.test.result == 'failure'"
    needs: [test]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      HTML_REPORT_URL_PATH: reports/guney/${{ github.run_id }}/${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages # Check out the gh-pages branch
      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Download zipped HTML report
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: ${{ env.HTML_REPORT_URL_PATH }}
      - name: Push HTML Report
        timeout-minutes: 3
        run: |
          git add .
          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
          while true; do
            git pull --rebase
            if [ $? -ne 0 ]; then
              echo "Failed to rebase. Please review manually."
              exit 1
            fi
            git push
            if [ $? -eq 0 ]; then
              echo "Successfully pushed HTML report to repo."
              exit 0
            fi
          done
      - name: Output Report URL as Workflow Annotation
        run: |
          FULL_HTML_REPORT_URL=https://guneyekiz.github.io/playwright/${{ env.HTML_REPORT_URL_PATH }}
          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
