name: Continuous Integration

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version here

      # Install npm dependencies and Playwright
      - name: Install dependencies and Playwright
        run: |
          npm ci
          npm install playwright

      # Install the browsers required by Playwright
      - name: Install Playwright browsers
        run: npx playwright install

      # Run Playwright tests and generate the HTML report
      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      # Upload the Playwright HTML report as an artifact
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      # Deploy the Playwright report to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success() # This ensures deployment only if previous steps were successful
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout --orphan gh-pages
          git rm -rf .
          cp -R playwright-report/* .
          git add .
          git commit -m "Deploy Playwright report to GitHub Pages" --allow-empty
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
