name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install playwright
      
      - name: Install Playwright browsers
        run: npx playwright install
      
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
      
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Checkout gh-pages branch or create it
        run: |
          git fetch origin gh-pages:gh-pages || true
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial commit on gh-pages"
            git push origin gh-pages
          fi
      
      - name: Deploy Playwright Report to gh-pages
        run: |
          git rm -rf . || true # Remove all files (clean slate)
          git clean -fdx # Remove untracked files and directories
          # Assuming 'playwright-report' is generated at the root
          cp -R playwright-report/ . || echo "Playwright report not found."
          git add -A
          git commit -m "Deploy updated Playwright report [skip ci]" || echo "No changes to commit."
          git push -f origin gh-pages
      
      - name: Output Playwright report URL
        run: |
         echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/index.html"
