name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        continue-on-error: true

      - name: Generate date and run number
        run: |
          # Format the date as 'YYYYMMDD'
          echo "CURRENT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          # Get the next run number for today, assume directories are named 'YYYYMMDD-run*'
          RUN_NUMBER=$(find . -type d -name "${{ env.CURRENT_DATE }}-run*" | wc -l | xargs)
          ((RUN_NUMBER++))
          # Write the run number with the prefixed date to the environment variable
          echo "TIMESTAMPED_DIR=${{ env.CURRENT_DATE }}-run${RUN_NUMBER}" >> $GITHUB_ENV
          mkdir -p ${{ env.TIMESTAMPED_DIR }}
          echo "Directory for reports: ${{ env.TIMESTAMPED_DIR }}"
        shell: bash

      - name: Copy Playwright report to timestamped directory
        run: cp -r playwright-report/* ${{ env.TIMESTAMPED_DIR }}

      - name: Zip Playwright report
        run: zip -r ${{ env.TIMESTAMPED_DIR }}.zip playwright-report/

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ env.TIMESTAMPED_DIR }}
          path: ${{ env.TIMESTAMPED_DIR }}.zip

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Stash package files to prevent checkout issues
        run: git stash push -- package-lock.json package.json

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "gh-pages" ]; then
            git reset --soft origin/gh-pages || true
          fi

      - name: Remove all except index.html and timestamped directories
        run: |
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name 'index.html' ! -name '${{ env.CURRENT_DATE }}-run*' -exec rm -rf {} + || true

      - name: Copy latest index.html to root
        run: cp ${{ env.TIMESTAMPED_DIR }}/index.html ./ || true

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Deploy Playwright report for run ${{ env.RUN_NUMBER }} on ${{ env.CURRENT_DATE }}"
          git push

      - name: Output Playwright report URL
        run: |
          echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/${{ env.TIMESTAMPED_DIR }}/index.html"
