name: CI and Deploy to GitHub Pages

on:  
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        continue-on-error: true

      - name: Generate date and run number
        id: run_info
        run: |
          CURRENT_DATE=$(date +%Y/%m/%d)
          echo "::set-output name=date::$CURRENT_DATE"
          RUN_NUMBER=$(find . -type d -path "./$CURRENT_DATE/*" | wc -l)
          ((RUN_NUMBER++))
          echo "::set-output name=run_number::$RUN_NUMBER"
          mkdir -p $CURRENT_DATE/$RUN_NUMBER
          echo "Directory for reports: $CURRENT_DATE/$RUN_NUMBER"
        shell: bash

      - name: Copy Playwright report to the directory for this run
        run: cp -r playwright-report/* ${{ steps.run_info.outputs.date }}/${{ steps.run_info.outputs.run_number }}

      - name: Zip the report for this run
        run: zip -r report-${{ steps.run_info.outputs.date }}-${{ steps.run_info.outputs.run_number }}.zip ${{ steps.run_info.outputs.date }}/${{ steps.run_info.outputs.run_number }}

      - name: Upload the zipped report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: report-${{ steps.run_info.outputs.date }}-${{ steps.run_info.outputs.run_number }}
          path: report-${{ steps.run_info.outputs.date }}-${{ steps.run_info.outputs.run_number }}.zip

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Stash package files to prevent checkout issues
        run: git stash push -- package-lock.json package.json

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          if [ "$(git rev-parse --abbrev-ref HEAD)" == "gh-pages" ]; then
            git reset --soft origin/gh-pages || true
          fi

      - name: Remove all except for the report directories and index.html
        run: |
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name 'index.html' ! -name '[0-9]*' -exec rm -rf {} +

      - name: Copy latest index.html to root
        run: cp ${{ steps.run_info.outputs.date }}/${{ steps.run_info.outputs.run_number }}/index.html index.html || true

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Deploy Playwright report for run ${{ steps.run_info.outputs.run_number }} on ${{ steps.run_info.outputs.date }}"
          git push -fu https://${{ secrets.ACCESS_TOKEN }}@github.com/guneyekiz/playwright gh-pages

      - name: Output Playwright report URL
        run: | 
          echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/${{ steps.run_info.outputs.date }}/${{ steps.run_info.outputs.run_number }}/index.html"
