name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright and browsers
        run: |
          npm install playwright
          npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Check if gh-pages branch exists
        id: check-branch
        run: |
          if git ls-remote --heads origin gh-pages; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Checkout gh-pages branch or initialize if doesn't exist
        run: |
          if [ "${{ steps.check-branch.outputs.exists }}" == "true" ]; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial commit on gh-pages"
            git push origin gh-pages
            git checkout -b gh-pages
          fi

      - name: Deploy Playwright Report
        run: |
          git rm -rf . || true
          git clean -fdx
          cp -R ../playwright-report/ . || echo "Copying Playwright report failed."
          git add .
          git diff --quiet || git commit -m "Deploy updated Playwright report"
          git push -f origin gh-pages

      - name: Output Playwright report URL
        run: |
         echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/"
