name: CI and Deploy to GitHub Pages

on:  
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci 

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        continue-on-error: true

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Checkout gh-pages branch
        run: |
          git fetch --depth=1
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Get current date for folder naming
        run: echo "DATE_FOLDER=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create report folder with the current date and copy the report
        run: |
          mkdir -p playwright-report/${{ env.DATE_FOLDER }}
          cp -r playwright-report/* playwright-report/${{ env.DATE_FOLDER }}/

      - name: Generate or update index.html with links to reports
        run: |
          if [ ! -f index.html ]; then
            echo "<html><head></head><body><ul>" > index.html
          else
            sed -i '/<\/ul>/d' index.html
          fi
          echo "<li><a href='./playwright-report/${{ env.DATE_FOLDER }}/index.html'>Report from ${{ env.DATE_FOLDER }}</a></li></ul></body></html>" >> index.html

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update reports for ${{ env.DATE_FOLDER }}"
          git push -u origin gh-pages

      - name: Output Playwright report URL
        run: | 
          echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/${{ env.DATE_FOLDER }}/index.html"
