name: CI and Deploy to GitHub Pages  

on:   
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        continue-on-error: true

      - name: Generate today's date
        id: today
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Generate running number for today
        id: run_number
        run: |
          printf -v today_num '%02d' "$(($(ls -d [0-9][0-9]-* 2>/dev/null | wc -l) + 1))"
          echo "::set-output name=run_number::$today_num"

      - name: Create timestamped directory for reports
        run: mkdir -p ${{ steps.today.outputs.date }}-${{ steps.run_number.outputs.run_number }}

      - name: Zip Playwright report
        run: zip -r ${{ steps.today.outputs.date }}-${{ steps.run_number.outputs.run_number }}/playwright-report.zip playwright-report/

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ steps.today.outputs.date }}-${{ steps.run_number.outputs.run_number }}
          path: ${{ steps.today.outputs.date }}-${{ steps.run_number.outputs.run_number }}/playwright-report.zip

      - name: Copy Playwright report to timestamped directory
        run: cp -r playwright-report/* ${{ steps.today.outputs.date }}-${{ steps.run_number.outputs.run_number }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Stash package files to prevent checkout issues
        run: git stash push -- package-lock.json package.json

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          fetch-depth: 0 # Necessary to get complete history

      - name: Remove old reports from root
        run: find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name '[0-9][0-9]-*' ! -name 'index.html' ! -name 'README.md' -exec rm -rf {} +

      - name: Update root index.html with latest report
        run: cp ${{ steps.today.outputs.date }}-${{ steps.run_number.outputs.run_number }}/index.html .

      - name: Commit Playwright report to gh-pages
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Deploy Playwright report ${GITHUB_SHA}"
          else
            echo "No changes to commit to gh-pages."
          fi

      - name: Push changes using PAT
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git push -fu origin gh-pages

      - name: Output Playwright report URL
        run: | 
          echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/${{ steps.today.outputs.date }}-${{ steps.run_number.outputs.run_number }}/"
