name: ci

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install
      
      - run: npx playwright test --reporter=html

      - uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}

      - run: cp -r playwright-report/* gh-pages/

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-pages
