name: ci

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install
      
      # Generate the Playwright report
      - run: npx playwright test --reporter=html
      
      # Upload the Playwright report as an artifact (optional, for viewing in the Actions tab)
      - uses: actions/upload-artifact@master
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 20

      # Checkout the gh-pages branch to a specific directory
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}

      # Copy the Playwright report to the gh-pages directory
      - name: Copy Playwright report to gh-pages
        run: cp -r playwright-report/* gh-pages/

      # Commit and push changes to the gh-pages branch
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-pages
