name: ci

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install
      
      # Generate the Playwright report
      - run: npx playwright test --reporter=html
      
      # Assuming playwright-report is the directory where reports are generated
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      # Assuming the Playwright report is named 'playwright-report'
      - name: Deploy Playwright report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success() # Only run this step if the previous steps were successful
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./playwright-report
