name: Continuous Integration and Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies and Playwright
        run: |
          npm ci
          npm install playwright
      
      - name: Install Playwright browsers
        run: npx playwright install
      
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
      
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      
      - name: Prepare for Deployment
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git stash --include-untracked
      
      - name: Deploy to gh-pages
        if: success()
        run: |
          # Check if the gh-pages branch exists and switch to it; otherwise, create it
          if git ls-remote --exit-code origin gh-pages; then
            echo "Fetching gh-pages branch."
            git fetch origin gh-pages:gh-pages
            git checkout gh-pages
          else
            echo "Creating gh-pages branch."
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
            git fetch origin
            git checkout gh-pages
          fi
          
          # Clean current branch's directory (gh-pages) except the .git directory
          git rm -rf .
          git clean -fdx -e .git

          # Restore files from stash or previous steps
          git checkout stash -- playwright-report || echo "No stash to apply."
          
          # Add and commit changes
          git add -f playwright-report/*
          if git status | grep -q "Changes to be committed"; then
            git commit -m "Update Playwright Report"
            git push -f origin gh-pages
          else
            echo "No changes to commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output Report URL
        run: |
         echo "Playwright report URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/playwright-report/index.html"
