name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm install playwright

      - name: Install browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload HTML report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/

  publish_report: 
    needs: test
    if: "success() || needs.test.result == 'failure'"
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get the current date and time
        id: date
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Create new report directory
        run: mkdir -p ${{ github.workspace }}/reports/${{ env.NOW }}

      - name: Download zipped HTML report
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: ${{ github.workspace }}/reports/${{ env.NOW }}

      - name: Move the report to the new directory
        run: mv ${{ github.workspace }}/playwright-report/* ${{ github.workspace }}/reports/${{ env.NOW }}/

      - name: Commit and Push the report to gh-pages
        run: |
          git add .
          git commit -m "Publish Playwright report for run ${{ github.run_id }} dated ${{ env.NOW }}"
          git push --set-upstream origin gh-pages
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
